name: Code Style Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Check Code Style
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@2.0.0
          with:
            preset: laravel
            verboseMode: true
            testMode: true
            configPath: "pint.json"
            pintVersion: 1.8.0
            onlyDirty: true
